# 这条指令指定 Nginx 工作进程运行的用户，使用 `www-data` 用户出于安全考虑
user www-data;

# 这个指令设置 Nginx 的工作进程数量。`auto` 参数表示自动设置工作进程的数量
worker_processes auto;

# 这个指令指定存放 Nginx 主进程 PID 的文件，系统使用这个 PID 文件来管理主进程
pid /run/nginx.pid;

# 这个指令用于包含额外的配置文件
include /etc/nginx/modules-enabled/*.conf;
include /etc/nginx/modules-available/*.conf;

# 新版
include /etc/nginx/modules/*.conf;

events {
    # 这个指令设置每个工作进程能够同时打开的连接数上限
    worker_connections 100;
}

http {
    # 启用高效的数据传输方式，将文件直接从磁盘传送到网络，绕过用户空间，提升传输性能
    sendfile on;

    # 减少TCP包的发送次数，优化传输效率，适合大量静态内容传输
    tcp_nopush on;

    # 控制mime.types文件中类型的哈希表大小
    types_hash_max_size 2048;

	# 包含默认类型
	include mime.types;

    # 设置默认的MIME类型
    default_type application/octet-stream;

    # 最大请求体
    client_max_body_size 1G;

    # 启用TLS协议版本，同时禁用已过时和不安全的SSLv3协议
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    # 服务器选择使用自己优先级较高的加密算法
	ssl_prefer_server_ciphers on;

    # 开启gzip压缩
    gzip on;

    server {
		listen 80;

		location / {
			root /app;
    		try_files $uri $uri/ /index.html;
		}
	}
}